---
title: "Iteration and listcols"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuious.color = "viridis",
  ggplot2.continuious.fill = "viridis"
  
)

scale_color_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


Set seed for reproducibility: 
```{r}
set.seed(12345)
```


# Lists

```{r}
vec_numeric = 1:4
vec_char = c("my", "name", "is", "vicky")

tibble(
  num = vec_numeric,
  char = vec_char
)
```

Different stuff with different lengths

```{r}
l = list(
    vec_numeric = 1:5,
    vec_char = LETTERS,
    matrix(1:10, nrow = 5, ncol = 2),
    summary = summary(rnorm(100))
)

```

Accessing lists: 

```{r}
l$vec_char # <-- extracting the character vector
l[[1]] # <-- shows you what the 1st element in the list is (replace w diff numbers to see different elements)
l[["summary"]] 
```


# Loops!

```{r}
list_norm_samples = 
  list(
    a = rnorm(20, 1, 5),
    b = rnorm(20, 0, 7),
    c = rnorm(20, 20, 5),
    d = rnorm(20, -45, 13)
  )
```

Using the mean and sd function from functions unit: 

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

   tibble(
    mean = mean_x, 
    sd = sd_x
  )
}
```

